
# 随机生成一个密码
# docker exec -it alist ./alist admin random
# 手动设置一个密码,`NEW_PASSWORD`是指你需要设置的密码
# docker exec -it alist ./alist admin set NEW_PASSWORD

# 记得给alist文件夹及子目录读写权限

version: "3.8"

services:
  # Alist 配置
  alist:
    container_name: alist
    image: xhofe/alist:latest
    restart: unless-stopped
    environment:
      - PUID=0     # 使用 root 用户ID
      - PGID=0     # 使用 root 组ID
      - UMASK=022  # 建议为022
    volumes:
      # Alist数据映射
      - ./etc/alist:/opt/alist/data
      # 与Aria2共享下载目录
      - /mnt/data/alist:/opt/alist/data/temp
    ports:
      # 宿主机5233端口映射到容器5244端口
      - "5233:5244"

services:  
  # Aria2-Pro 配置  
  Aria2-Pro:  
    container_name: aria2-pro  
    image: p3terx/aria2-pro  
    environment:  
      # 用户和组ID配置，对应无特权用户nobody  
      - PUID=0  
      - PGID=0
      - UMASK_SET=022  
      # RPC认证与端口设置  
      - RPC_SECRET=123456   # 访问密码  
      - RPC_PORT=6800  
      - LISTEN_PORT=6888  
      # 缓存与网络配置  
      - DISK_CACHE=64M  
      - IPV6_MODE=false  
      # 追踪器与时间区域  
      - UPDATE_TRACKERS=true  
      - CUSTOM_TRACKER_URL=  
      - TZ=Asia/Shanghai  
      # 特殊模式：rclone集成  
      - SPECIAL_MODE=rclone  
    volumes:  
      # 配置与下载目录映射  
      - ./aria2-config:/config  
      - /mnt/data/alist:/downloads  
      # Alist与Aria2的临时下载路径共享  
      - /mnt/data/alist:/opt/alist/data/temp
    # 网络模式设定，默认为主机模式以简化IPv6配置  
    network_mode: host  
    # 可选桥接模式及端口映射注释（如需使用，请取消相应注释）  
    # network_mode: bridge  
    # ports:  
    #   - 6800:6800  
    #   - 6888:6888  
    #   - 6888:6888/udp  
    restart: unless-stopped  
    logging:  
      driver: json-file  
      options:  
        max-size: 1m  
  
  # AriaNg 配置  
  AriaNg:  
    container_name: ariang  
    image: p3terx/ariang  
    command: --port 6880 --ipv6  
    network_mode: host  
    # 桥接模式配置示例（如需使用，请取消相应注释）  
    # network_mode: bridge  
    # ports:  
    #   - 6880:6880  
    restart: unless-stopped  
    logging:  
      driver: json-file  
      options:  
        max-size: 1m  

        
  # qBittorrent配置
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # 环境变量配置
    environment:
      - PUID=0  # 使用 root 用户ID
      - PGID=0  # 使用 root 组ID
      - TZ=Etc/UTC  # 设置时区为UTC
      - WEBUI_PORT=8080  # Web界面端口
      - TORRENTING_PORT=6881  # 下载端口
    # 数据卷挂载
    volumes:
      - ./config:/config
      - /mnt/data/alist:/downloads
      # 与Alist共享下载目录
      - /mnt/data/alist:/opt/alist/data/temp
    # 端口映射
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
